apiKey: null
artifactDirectory: null
clusterId: cliccf10g
command: "python minGPT-torch/minGPT.py"
container: idkmoon/gpt2:v1
containerUser: null
experimentEnv: null
ignoreFiles: null
isPreemptible: false
machineType: "P4000"
modelPath: null
modelType: null
name: minGPT-single
no-logs: true
ports: null
projectId: prncecs0s
registryPassword: null
registryUrl: null
registryUsername: null
tag: null
tags: null
tensorboard: false
tensorboard_set: null
workingDirectory: null
workspace: ./
workspacePassword: null
workspaceRef: null
workspaceUsername: null
